README.rst
coscmd/cos_client.py
coscmd/cos_cmd.py
setup.py

Signed-off-by: liuchang0812 <liuchang0812@gmail.com>
(cherry picked from commit abbf3d72a11cf1bc1359532f21774159628b1887)

cleanup: fix encoding problem

---

coscmd/cos_client.py

ignore etag

---

.travis.yml
coscmd/cos_client.py
coscmd/test.py

Fix little bugs

---

coscmd/cos_auth.py
coscmd/cos_client.py
coscmd/cos_cmd.py
coscmd/test_bucket.py
coscmd/test_object.py

Add put/get bucket/object ACL interfaces and test file

Add put/get bucket/object ACL interfaces

---

coscmd/cos_client.py
coscmd/cos_cmd.py
tox.ini

Signed-off-by: liuchang0812 <liuchang0812@gmail.com>
现在的返回码和颜色渲染如下：

fix return code of uploading

---

coscmd/cos_client.py

Fix upload empty folder bug

---

coscmd/cos_cmd.py

Fix rt message

---

coscmd/cos_client.py
coscmd/cos_cmd.py

Update exception and rt message

Update breakpoint rt message

---

coscmd/cos_client.py
coscmd/cos_cmd.py

Del view bar

---

coscmd/cos_client.py
coscmd/cos_cmd.py
setup.py

Fix info bug

---

coscmd/cos_client.py

Update error message

---

coscmd/cos_auth.py
coscmd/cos_client.py

Fix multi delete

---

coscmd/cos_client.py
coscmd/cos_cmd.py
requirements.txt

Fix view bar

---

coscmd/cos_client.py
coscmd/cos_cmd.py

Add signurl

---

coscmd/cos_client.py
coscmd/cos_cmd.py

Multi download

---

coscmd/cos_client.py

Del multi-thread download

---

coscmd/cos_client.py
coscmd/test.py

Fix delete and download encode bug

---

coscmd/cos_client.py
coscmd/cos_cmd.py

Fix encode problem in windows

---

.travis.yml
coscmd/cos_cmd.py
requirements.txt

Fix secret

---

coscmd/cos_cmd.py
requirements.txt

Add custom region, log path, configuration path

Fix region

---

coscmd/cos_cmd.py

fix log path

---

coscmd/cos_auth.py
coscmd/cos_client.py
coscmd/cos_cmd.py
coscmd/cos_threadpool.py
coscmd/test.py

last pull request contain a lot of format lines and make it difficult to check, this pull request base on the HEAD version of code and just py2 to py3 commit.
Please check the code and test it.
Thank you very much~

py2 to py3

---

coscmd/cos_client.py
coscmd/cos_cmd.py

Signed-off-by: Chang Liu <liuchang0812@gmail.com>

endpoint feature

---

coscmd/cos_client.py
coscmd/cos_cmd.py
coscmd/test.py

1. support download with http_headers
2. support endpoint copysource

Feature download header
